name: cyberlab-glpi-n8n

services:
  glpi:
    image: glpi/glpi:latest
    container_name: glpi
    restart: unless-stopped
    depends_on:
      - db
    env_file: .env
    ports:
      - "8080:80"
    volumes:
      - glpi_data:/var/glpi
    networks:
      - lab-net

  db:
    image: mysql:8.0
    container_name: glpi-db
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${GLPI_DB_NAME}
      MYSQL_USER: ${GLPI_DB_USER}
      MYSQL_PASSWORD: ${GLPI_DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lab-net

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - TZ=${GENERIC_TIMEZONE}
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - lab-net

volumes:
  glpi_data:
  db_data:
  n8n_data:

networks:
  lab-net:
    driver: bridge
